language: python

matrix:
  include:
    - name: "Python 3.5"
      python: 3.5
      sudo: true
    - name: "Python 3.6"
      python: 3.6
      sudo: true
    - name: "Python 3.7"
      python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install --upgrade pip setuptools pytest
  - pip install coverage nose ordered-set polib pylint requests six
  - pip install Sphinx==1.7.6
  - pip install https://github.com/rhinstaller/pocketlint/zipball/master

script:
  - travis_wait env NOSE_IGNORE_CONFIG_FILES=y make check coverage docs COVERAGE=coverage

notifications:
  email:
    on_success: change
    on_failure: change
